services:
  webapp:
    build: .
    ports:
      - "8081:80"
    environment:
      C218_DataStore_DBName: C218
      C218_DataStore_Host: db
      C218_DataStore_Pass: myPassword
      C218_DataStore_User: C218_SA
      C218_SecurityKey: toto
    links:
      - db
    networks:
      - default

  db:
    image: mysql
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: C218
      MYSQL_USER: C218_SA
      MYSQL_PASSWORD: myPassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8082:80
    environment:
      MYSQL_USER: C218_SA
      MYSQL_PASSWORD: myPassword
      MYSQL_ROOT_PASSWORD: root

volumes:
  persistent: